### ISSUE TITLE
after re-projecting, I had to "zoom to layer" for the concave hull to become visible again

### ISSUE THREAD

**Issue by michaelkirk** [frewsxcv/rgis#89]
From https://github.com/georust/geo/pull/912#issuecomment-1261381171:

Jump ahead to 30s or so for the relevant behavior:

https://user-images.githubusercontent.com/217057/192873077-edc9def4-e195-4337-99a0-38dc68df7fa7.mp4

**Comment by frewsxcv** [comment]
done in https://github.com/frewsxcv/rgis/commit/a6806d17f0cdf5c25160c63d64c612c6b7eb6f01

open a new issue if you find any bugs with it!

**Comment by michaelkirk** [comment]
Something different, but still wrong, is happening - I now see an inexplicable layer of color appear after projecting.

Here's the full sequence of actions:

https://user-images.githubusercontent.com/217057/195947068-28133843-3de3-40d3-a7aa-2b8c46658628.mp4

And I took a couple screengrabs from the video:

**screenshot before projecting**
<img width="553" alt="Screen Shot 2022-10-14 at 2 31 35 PM" src="https://user-images.githubusercontent.com/217057/195947363-d5e1bcd5-afb1-4b00-9f99-d4e8107bad03.png">

**screenshot after projecting**
<img width="551" alt="Screen Shot 2022-10-14 at 2 31 45 PM" src="https://user-images.githubusercontent.com/217057/195947358-fc2fba8c-3aca-4ca1-a2f3-8c862b41a4cc.png">
(what is that orange layer? it disappears when scrolling. Note that it's the same color as the points layer)


It disappears as soon as I start to zooming out, so it maybe isn't a huge usability problem in practice, but it feels wrong.

**Comment by frewsxcv** [comment]
@michaelkirk https://github.com/frewsxcv/rgis/issues/94
